using System;
using System.ComponentModel;

namespace A2G_Trainer_XP.Model
{
    public static class PlayerEnums
    {
        public static string GetDescription(Enum value)
        {
            var f = value.GetType().GetField(value.ToString());
            var attributes = (DescriptionAttribute[])f.GetCustomAttributes(typeof(DescriptionAttribute), false);
            return attributes.Length > 0 ? attributes[0].Description : value.ToString();
        }

        public enum AddressType
        {
            OWN,
            OPPONENT,
            ALL,
            DYNAMIC
        }

        public enum AddressKey
        {
            ID,
            AGE,
            FIRSTNAME,
            LASTNAME,
            LEVEL,
            FORM,
            SKIN,
            HAIR,
            CONDITION,
            FRESHNESS,
            NATIONALITY,
            POSITION,
            SECONDARY_1,
            SECONDARY_2,
            SKILLS,
            NEG_SKILLS,
            PERSONALITY,
            CHARACTER,
            HEALTH,
            UNHAPPY,
            HAPPY,
            INJURED_DAYS,
            INJURY,
            VULNERABLE,
            BANNED_MATCHES,
            DOPED,
            YELLOW_CARDS,
            SALARY,
            SHOWUP,
            GOALS_BONUS,
            TRANSFER_FEE,
            CONTRACT_DURATION,
            CONTRACT_DETAILS,
            YEARS_IN_CLUB,
            CAREER,
            CLUB_ID,
            CLUB_COUNTRY
        }

        public enum Character : byte
        {
            Normal         = 0,
            Hitzkopf       = 1 << 0,
            Frohnatur      = 1 << 1,
            MannOhneNerven = 1 << 2,
            Nervenbuendel  = 1 << 3,
            Phlegma        = 1 << 4,
            Geldgeier      = 1 << 5,
            Musterprofi    = 1 << 6,
            Skandalnudel   = 1 << 7
        }
        public enum Career : byte
        {
            None = 0,
            Unknown0 = 1 << 0,
            Unknown1 = 1 << 1,
            Unknown2 = 1 << 2,
            Unknown3 = 1 << 3,
            Unknown4 = 1 << 4,
            Unknown5 = 1 << 5,
            Unknown6 = 1 << 6,
            Retires  = 1 << 7
        }
        public enum Contract : byte
        {
            None             = 0,
            Leased           = 1 << 0,
            BuyOption        = 1 << 1,
            Unknown          = 1 << 2,
            JoinedThisSeason = 1 << 3,
            OptionPlayer     = 1 << 4,
            OptionClub       = 1 << 5,
            Seated           = 1 << 6,
            Unset            = 1 << 7
        }
        public enum Country : byte
        {
            Sonstige        =  0,
            [Description("Ägypten")]
            Aegypten        =  1,
            Albanien        =  2,
            Algerien        =  3,
            Argentinien     =  4,
            Australien      =  5,
            Belgien         =  6,
            Bolivien        =  7,
            Brasilien       =  8,
            Bulgarien       =  9,
            Chile           = 10,
            China           = 11,
            [Description("Costa Rica")]
            CostaRica       = 12,
            Dänemark        = 13,
            Deutschland     = 14,
            Ecuador         = 15,
            England         = 16,
            Estland         = 17,
            [Description("Färörer Inseln")]
            FaeroererInseln = 18,
            Finnland        = 19,
            Frankreich      = 20,
            Georgien        = 21,
            Ghana           = 22,
            Griechenland    = 23,
            Holland         = 24,
            Irland          = 25,
            Island          = 26,
            Israel          = 27,
            Italien         = 28,
            Jamaika         = 29,
            Japan           = 30,
            Kamerun         = 31,
            Kanada          = 32,
            Kolumbien       = 33,
            Kroatien        = 34,
            Lettland        = 35,
            Liberia         = 36,
            Litauen         = 37,
            Luxemburg       = 38,
            Malta           = 39,
            Marokko         = 40,
            Mexiko          = 41,
            Moldavien       = 42,
            Neuseeland      = 43,
            Nigeria         = 44,
            Nordirland      = 45,
            Norwegen        = 46,
            [Description("Österreich")]
            Oesterreich     = 47,
            Paraguay        = 48,
            Peru            = 49,
            Polen           = 50,
            Portugal        = 51,
            [Description("Puerto Rico")]
            PuertoRico      = 52,
            [Description("Rumänien")]
            Rumaenien       = 53,
            Russland        = 54,
            [Description("San Marino")]
            SanMarino       = 55,
            [Description("Saudi Arabien")]
            SaudiArabien    = 56,
            Schottland      = 57,
            Schweden        = 58,
            Schweiz         = 59,
            Senegal         = 60,
            Slowakei        = 61,
            Slowenien       = 62,
            Spanien         = 63,
            [Description("Südkorea")]
            Suedkorea       = 64,
            Tschechien      = 65,
            Tunesien        = 66,
            [Description("Türkei")]
            Tuerkei         = 67,
            Ukraine         = 68,
            Ungarn          = 69,
            Uruguay         = 70,
            USA             = 71,
            Venezuela       = 72,
            Wales           = 73,
            Zaire           = 74,
            Zypern          = 75
        }
        public enum HairColor : byte
        {
            Hellblond = 0,
            Blond     = 1,
            Braun     = 2,
            Rot       = 3,
            Schwarz   = 4,
            Glatze    = 5
        }
        public enum Happy : byte
        {
            None                 = 0,
            TollerVertrag        = 1 << 0,
            TollePraemien        = 1 << 1,
            TolleStimmung        = 1 << 2,
            TollerVertragDoppelt = 1 << 3,
            TollerTrainer        = 1 << 4
        }
        public enum Health : byte
        {
            Normal         = 0,
            Robustheit     = 1 << 0,
            Anfaelligkeit = 1 << 1,
            Knieprobleme   = 1 << 2
        }
        public enum Personality : ushort
        {
            None                 = 0,
            Fuehrungsperson      = 1 <<  0,
            Kaempfernatur        = 1 <<  1,
            Trainingsweltmeister = 1 <<  2,
            Trainingsfaul        = 1 <<  3,
            Treter               = 1 <<  4,
            FairPlayer           = 1 <<  5,
            Schwalbenkoenig      = 1 <<  6,
            Allrounder           = 1 <<  7,
            FlexiblePlayer       = 1 <<  8,
            Heimspieler          = 1 <<  9,
            AuswaertsSpieler     = 1 << 10,
            Talent               = 1 << 11
        }
        public enum Position : byte
        {
            None =  0,
            TO   =  1,
            L    =  2,
            MD   =  3,
            LV   =  4,
            RV   =  5,
            RM   =  6,
            LM   =  7,
            DM   =  8,
            OM   =  9,
            S    = 10
        }
        public enum Skills : ushort
        {
            None            = 0,
            Elfmetertoeter  = 1 <<  0,
            StarkeReflexe   = 1 <<  1,
            Herauslaufen    = 1 <<  2,
            Fangsicherheit  = 1 <<  3,
            Fausten         = 1 <<  4,
            Ballsicherheit  = 1 <<  5,
            Kopfball        = 1 <<  0,
            Zweikampf       = 1 <<  1,
            Schnelligkeit   = 1 <<  2,
            Schusskraft     = 1 <<  3,
            Freistoesse     = 1 <<  4,
            Flanken         = 1 <<  5,
            Torinstinkt     = 1 <<  6,
            Laufstaerke     = 1 <<  7,
            Technik         = 1 <<  8,
            Spielmacher     = 1 <<  9,
            Beidfuessigkeit = 1 << 10,
        }
        public enum SkinColor : byte
        {
            Fair  = 0,
            Dark  = 1,
            Black = 2
        }
        public enum Unhappy : ushort
        {
            None                  = 0,
            WillEndlichSpielen    = 1 <<  0,
            WillMehrGeld          = 1 <<  1,
            MiesePraemien         = 1 <<  2,
            GehtNichtNachLeistung = 1 <<  3,
            FalschePosition       = 1 <<  4,
            ScheissVertrag        = 1 <<  5,
            MieseMannschaft       = 1 <<  6,
            SchlechteStimmung     = 1 <<  7,
            VerletztUndNieBesucht = 1 <<  8,
            UngerechteBehandlung  = 1 <<  9,
            BloedeFans            = 1 << 10,
            BloedeMitspieler      = 1 << 11,
            ScheissTrainer        = 1 << 12,
            VerhandlungGeplatzt   = 1 << 13,
            ScheissManager        = 1 << 14,
            ScheissNachwuchsrunde = 1 << 15
        }
        /* ToDo: Fill with injury names
        public enum Injury : byte
        {
           =   0,
           =   1,
           =   2,
           =   3,
           =   4,
           =   5,
           =   6,
           =   7,
           =   8,
           =   9,
           =  10,
           =  11,
           =  12,
           =  13,
           =  14,
           =  15,
           =  16,
           =  17,
           =  18,
           =  19,
           =  20,
           =  21,
           =  22,
           =  23,
           =  24,
           =  25,
           =  26,
           =  27,
           =  28,
           =  29,
           =  30,
           =  31,
           =  32,
           =  33,
           =  34,
           =  35,
           =  36,
           =  37,
           =  38,
           =  39,
           =  40,
           =  41,
           =  42,
           =  43,
           =  44,
           =  45,
           =  46,
           =  47,
           =  48,
           =  49,
           =  50,
           =  51,
           =  52,
           =  53,
           =  54,
           =  55,
           =  56,
           =  57,
           =  58,
           =  59,
           =  60,
           =  61,
           =  62,
           =  63,
           =  64,
           =  65,
           =  66,
           =  67,
           =  68,
           =  69,
           =  70,
           =  71,
           =  72,
           =  73,
           =  74,
           =  75,
           =  76,
           =  77,
           =  78,
           =  79,
           =  80,
           =  81,
           =  82,
           =  83,
           =  84,
           =  85,
           =  86,
           =  87,
           =  88,
           =  89,
           =  90,
           =  91,
           =  92,
           =  93,
           =  94,
           =  95,
           =  96,
           =  97,
           =  98,
           =  99,
           = 100,
           = 101,
           = 102,
           = 103,
           = 104,
           = 105,
           = 106,
           = 107,
           = 108,
           = 109,
           = 110,
           = 111,
           = 112,
           = 113,
           = 114,
           = 115,
           = 116,
           = 117,
           = 118,
           = 119,
           = 120,
           = 121,
           = 122,
           = 123,
           = 124,
           = 125,
           = 126,
           = 127,
           = 128,
           = 129,
           = 130,
           = 131,
           = 132,
           = 133,
           = 134,
           = 135,
           = 136,
           = 137,
           = 138,
           = 139,
           = 140,
           = 141,
           = 142,
           = 143,
           = 144,
           = 145,
           = 146,
           = 147,
           = 148,
           = 149,
           = 150,
           = 151,
           = 152,
           = 153,
           = 154,
           = 155,
           = 156,
           = 157,
           = 158,
           = 159,
           = 160,
           = 161,
           = 162,
           = 163,
           = 164,
           = 165,
           = 166,
           = 167,
           = 168,
           = 169,
           = 170,
           = 171,
           = 172,
           = 173,
           = 174,
           = 175,
           = 176,
           = 177,
           = 178,
           = 179,
           = 180,
           = 181,
           = 182,
           = 183,
           = 184,
           = 185,
           = 186,
           = 187,
           = 188,
           = 189,
           = 190,
           = 191,
           = 192,
           = 193,
           = 194,
           = 195,
           = 196,
           = 197,
           = 198,
           = 199,
           = 200,
           = 201,
           = 202,
           = 203,
           = 204,
           = 205,
           = 206,
           = 207,
           = 208,
           = 209,
           = 210,
           = 211,
           = 212,
           = 213,
           = 214,
           = 215,
           = 216,
           = 217,
           = 218,
           = 219,
           = 220,
           = 221,
           = 222,
           = 223,
           = 224,
           = 225,
           = 226,
           = 227,
           = 228,
           = 229,
           = 230,
           = 231,
           = 232,
           = 233,
           = 234,
           = 235,
           = 236,
           = 237,
           = 238,
           = 239,
           = 240,
           = 241,
           = 242,
           = 243,
           = 244,
           = 245,
           = 246,
           = 247,
           = 248,
           = 249,
           = 250,
           = 251,
           = 252,
           = 253,
           = 254,
           = 255
        }
        */
    }
}
